// Code generated by Kitex v0.7.0. DO NOT EDIT.

package shop

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "main/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateProtuct(ctx context.Context, req *api.CreateRequest, callOptions ...callopt.Option) (r *api.CreateResponse, err error)
	RequsetAll(ctx context.Context, callOptions ...callopt.Option) (r *api.ResqResponse, err error)
	RequsetByName(ctx context.Context, req *api.ProductReqByName, callOptions ...callopt.Option) (r *api.ResqResponse, err error)
	RequsetByPrice(ctx context.Context, req *api.ProductReqByPrice, callOptions ...callopt.Option) (r *api.ResqResponse, err error)
	Buy(ctx context.Context, req *api.BuyReq, callOptions ...callopt.Option) (r *api.BuyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kShopClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kShopClient struct {
	*kClient
}

func (p *kShopClient) CreateProtuct(ctx context.Context, req *api.CreateRequest, callOptions ...callopt.Option) (r *api.CreateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProtuct(ctx, req)
}

func (p *kShopClient) RequsetAll(ctx context.Context, callOptions ...callopt.Option) (r *api.ResqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequsetAll(ctx)
}

func (p *kShopClient) RequsetByName(ctx context.Context, req *api.ProductReqByName, callOptions ...callopt.Option) (r *api.ResqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequsetByName(ctx, req)
}

func (p *kShopClient) RequsetByPrice(ctx context.Context, req *api.ProductReqByPrice, callOptions ...callopt.Option) (r *api.ResqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequsetByPrice(ctx, req)
}

func (p *kShopClient) Buy(ctx context.Context, req *api.BuyReq, callOptions ...callopt.Option) (r *api.BuyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Buy(ctx, req)
}
